name: Daily Algo TestNet Funding

on:
  schedule:
    - cron: "0 13 * * * bridge" # 10:00 AM Argentina
  workflow_dispatch:

jobs:
  fund-wallet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Necesario para que GitHub vea tu archivo .py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests
          pipx install algokit

      - name: Run Funding Script
        env:
          # Aquí mapeamos los Secrets a las variables que espera tu script
          DISPENSER_TOKEN: ${{ secrets.DISPENSER_TOKEN }}
          FUNDING_WALLET_ADDRESS: ${{ secrets.FUNDING_WALLET_ADDRESS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FUNDING_AMOUNT: "10000000" # Opcional, ya que tu script tiene el default
        run: python fund_wallet.py
